// this is where you actually config your UI
// lowest commented code are auto generated by vite react

import { useEffect,useState } from "react";
        // copy the address from forwared port for uvicorn server in github 
const API_URL= "https://---.app.github.dev"; //this should be a string 

export default function App(){
  const [items,setItems]=useState([]);
  useEffect(()=>{
    fetch(`${API_URL}/items`)
      .then(res=>res.json())
      .then(setItems);
  },[]);

  const addItem=async () =>{
    try{
      const res=await fetch(`${API_URL}/items`,{
        method:"POST",
        headers:{"Content-Type":"application/json"},
        body:JSON.stringify({name:"Hello yihawww"})
      });

      if (!res.ok) {
        const errBody = await res.json();
        console.error("Backend error:", errBody);
        return;
      }

      const updated=await fetch(`${API_URL}/items`).then(r=>r.json());
      setItems(updated);
    } catch (err){
      console.error("error:", err);
    } 
  };

  return(
    <div style={{padding:20}}>
      <h1>FastAPI + MongoDB + React</h1>
      <button onClick={addItem}>Add item</button>
      <ul>
        {items.map(i=>(
          <li key={i._id}>{i.name}</li>
        ))}
      </ul>
    </div>
  );
}


//============================================================================================
// import { useState } from 'react'
// import reactLogo from './assets/react.svg'
// import viteLogo from '/vite.svg'
// import './App.css'

// function App() {
//   const [count, setCount] = useState(0)

//   return (
//     <>
//       <div>
//         <a href="https://vite.dev" target="_blank">
//           <img src={viteLogo} className="logo" alt="Vite logo" />
//         </a>
//         <a href="https://react.dev" target="_blank">
//           <img src={reactLogo} className="logo react" alt="React logo" />
//         </a>
//       </div>
//       <h1>Vite + React</h1>
//       <div className="card">
//         <button onClick={() => setCount((count) => count + 1)}>
//           count is {count}
//         </button>
//         <p>
//           Edit <code>src/App.jsx</code> and save to test HMR
//         </p>
//       </div>
//       <p className="read-the-docs">
//         TEST dari anjel
//       </p>
//     </>
//   )
// }

// export default App
//========================================================================================